name: image_captioning
channels:
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::r-evaluate
  - pandas
  - conda-forge::matplotlib
  - tqdm
  - nltk
  - seaborn